/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.avaliacaods;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author rayli
 */
public class Treinando extends javax.swing.JFrame {

    /**
     * Creates new form Treinando
     */
    public Treinando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoCor = new javax.swing.ButtonGroup();
        GrupoEstilo = new javax.swing.ButtonGroup();
        GrupoTamanho = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        Painel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextArea();
        Menu = new javax.swing.JMenuBar();
        Opcoes = new javax.swing.JMenu();
        Limpar = new javax.swing.JMenuItem();
        Fonte = new javax.swing.JMenu();
        Cor = new javax.swing.JMenu();
        Azul = new javax.swing.JRadioButtonMenuItem();
        Preto = new javax.swing.JRadioButtonMenuItem();
        Verde = new javax.swing.JRadioButtonMenuItem();
        Estilo = new javax.swing.JMenu();
        Normal = new javax.swing.JRadioButtonMenuItem();
        Negrito = new javax.swing.JRadioButtonMenuItem();
        Italico = new javax.swing.JRadioButtonMenuItem();
        Tam12 = new javax.swing.JMenu();
        jRadioButtonMenuItem7 = new javax.swing.JRadioButtonMenuItem();
        Tam14 = new javax.swing.JRadioButtonMenuItem();
        Tam16 = new javax.swing.JRadioButtonMenuItem();
        Tam18 = new javax.swing.JRadioButtonMenuItem();
        Separador = new javax.swing.JPopupMenu.Separator();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste");

        Texto.setColumns(20);
        Texto.setRows(5);
        jScrollPane1.setViewportView(Texto);

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(Painel);

        Opcoes.setText("Opções");

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        Opcoes.add(Limpar);

        Fonte.setText("Fonte");

        Cor.setText("Cor");

        GrupoCor.add(Azul);
        Azul.setText("Azul");
        Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AzulActionPerformed(evt);
            }
        });
        Cor.add(Azul);

        GrupoCor.add(Preto);
        Preto.setSelected(true);
        Preto.setText("Preto");
        Preto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PretoActionPerformed(evt);
            }
        });
        Cor.add(Preto);

        GrupoCor.add(Verde);
        Verde.setText("Verde");
        Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerdeActionPerformed(evt);
            }
        });
        Cor.add(Verde);

        Fonte.add(Cor);

        Estilo.setText("Estilo");

        GrupoEstilo.add(Normal);
        Normal.setSelected(true);
        Normal.setText("Normal");
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });
        Estilo.add(Normal);

        GrupoEstilo.add(Negrito);
        Negrito.setText("Negrito");
        Negrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegritoActionPerformed(evt);
            }
        });
        Estilo.add(Negrito);

        GrupoEstilo.add(Italico);
        Italico.setText("Italico");
        Estilo.add(Italico);

        Fonte.add(Estilo);

        Tam12.setText("Tamanho");

        GrupoTamanho.add(jRadioButtonMenuItem7);
        jRadioButtonMenuItem7.setSelected(true);
        jRadioButtonMenuItem7.setText("12");
        Tam12.add(jRadioButtonMenuItem7);

        GrupoTamanho.add(Tam14);
        Tam14.setText("14");
        Tam12.add(Tam14);

        GrupoTamanho.add(Tam16);
        Tam16.setText("16");
        Tam12.add(Tam16);

        GrupoTamanho.add(Tam18);
        Tam18.setText("18");
        Tam12.add(Tam18);

        Fonte.add(Tam12);

        Opcoes.add(Fonte);
        Opcoes.add(Separador);

        Sair.setText("Sair");
        Opcoes.add(Sair);

        Menu.add(Opcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        
        Texto.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AzulActionPerformed
        // TODO add your handling code here:
        Texto.setForeground(Color.BLUE);
    }//GEN-LAST:event_AzulActionPerformed

    private void PretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PretoActionPerformed
        // TODO add your handling code here:
         Texto.setForeground(Color.BLACK);
    }//GEN-LAST:event_PretoActionPerformed

    private void VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerdeActionPerformed
        // TODO add your handling code here:
         Texto.setForeground(Color.GREEN);
    }//GEN-LAST:event_VerdeActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        // TODO add your handling code here:
        
        Texto.setFont(Font.BOLD);
    }//GEN-LAST:event_NormalActionPerformed

    private void NegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegritoActionPerformed
        // TODO add your handling code here:
         Texto.setFont(Font.ITALIC);
    }//GEN-LAST:event_NegritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Treinando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Treinando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Treinando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Treinando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Treinando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem Azul;
    private javax.swing.JMenu Cor;
    private javax.swing.JMenu Estilo;
    private javax.swing.JMenu Fonte;
    private javax.swing.ButtonGroup GrupoCor;
    private javax.swing.ButtonGroup GrupoEstilo;
    private javax.swing.ButtonGroup GrupoTamanho;
    private javax.swing.JRadioButtonMenuItem Italico;
    private javax.swing.JMenuItem Limpar;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JRadioButtonMenuItem Negrito;
    private javax.swing.JRadioButtonMenuItem Normal;
    private javax.swing.JMenu Opcoes;
    private javax.swing.JPanel Painel;
    private javax.swing.JRadioButtonMenuItem Preto;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JPopupMenu.Separator Separador;
    private javax.swing.JMenu Tam12;
    private javax.swing.JRadioButtonMenuItem Tam14;
    private javax.swing.JRadioButtonMenuItem Tam16;
    private javax.swing.JRadioButtonMenuItem Tam18;
    private javax.swing.JTextArea Texto;
    private javax.swing.JRadioButtonMenuItem Verde;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
